// @vitest-environment jsdom
import { act, createElement } from 'react'
import { createRoot } from 'react-dom/client'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import App from './App'
import { QueueOverview } from './components/QueueOverview'
import { COLOR_NAMES, TICK_MS, createTide, launch, levelsFor, stepTide } from './game/tide'
import { TIDE_SAVE_KEY, readTideProgress } from './storage/tideProgress'
import { readRecords } from './storage/tideRecords'

let root: ReturnType<typeof createRoot>
let host: HTMLDivElement
beforeEach(() => {
  vi.useFakeTimers()
  Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true })
  localStorage.clear()
  for (const key of ['jellyOrbitWelcomeV1', 'jellyOrbitIceIntroV1', 'jellyOrbitShellIntroV1']) localStorage.setItem(key, 'seen')
  vi.spyOn(window, 'scrollTo').mockImplementation(() => {})
  host = document.createElement('div'); document.body.append(host)
  root = createRoot(host)
})
afterEach(async () => {
  await act(() => root.unmount())
  host.remove(); vi.useRealTimers(); vi.restoreAllMocks()
})
async function click(selector: string) {
  const button = host.querySelector<HTMLButtonElement>(selector)
  expect(button, selector).not.toBeNull()
  expect(button!.disabled).toBe(false)
  await act(() => button!.click())
}
async function renderGame() {
  await act(() => root.render(createElement(App)))
  await click('.home-play')
}
it('opens on the home screen and defers the first-play tutorial until entering a journey', async () => {
  localStorage.removeItem('jellyOrbitWelcomeV1')
  await act(() => root.render(createElement(App)))
  expect(host.querySelector('.home-play')!.textContent).toContain('開始冒險')
  expect(host.querySelector('.game-screen')!.hasAttribute('hidden')).toBe(true)
  expect(host.querySelector('[role="dialog"]')).toBeNull()
  await click('.home-difficulties button:nth-child(3)')
  expect(host.querySelector('.home-resume')!.textContent).toContain('困難 · 第 01 關')
  expect(readTideProgress()).toEqual([])
  await click('.home-play')
  expect(host.querySelector('[role="dialog"]')!.getAttribute('aria-label')).toBe('遊戲說明')
  expect(host.querySelector('.home-screen')).toBeNull()
  expect(host.querySelector('.game-screen')!.hasAttribute('hidden')).toBe(false)
  expect(host.querySelectorAll('.dock-slot')).toHaveLength(4)
  expect(localStorage.getItem('jellyOrbitDifficultyV1')).toBe('hard')
})
it('pauses on home and preserves the board, lane order, berth and undo history on return', async () => {
  localStorage.setItem('jellyOrbitDifficultyV1', 'hard')
  await renderGame()
  await click('.launch-button')
  const board = host.querySelector('.pixel-board')!.innerHTML
  const lanes = host.querySelector('.lanes')!.innerHTML
  const reserved = host.querySelector('.dock-slot.reserved')!
  const partner = reserved.getAttribute('data-jelly-id')
  const berth = [...host.querySelectorAll('.dock-slot')].indexOf(reserved)
  await click('.home-button')
  expect(host.querySelector('.home-play')!.textContent).toContain('繼續冒險')
  await act(() => vi.advanceTimersByTime(20000))
  expect(host.querySelector('.pixel-board')!.innerHTML).toBe(board)
  expect(host.querySelector('.dock-capacity')!.textContent).toContain('返航中 1')
  await click('.home-difficulties button:nth-child(2)')
  await click('.home-difficulties button:nth-child(3)')
  await click('.home-play')
  expect(host.querySelectorAll('.dock-slot')[berth].getAttribute('data-jelly-id')).toBe(partner)
  expect(host.querySelector('.lanes')!.innerHTML).toBe(lanes)
  await click('.game-tools button:first-child')
  expect(host.querySelector('.dock-capacity')!.textContent).toBe('返航中 0 · 已停泊 0')
  await click('.header-actions button[aria-label="暫停遊戲"]')
  await click('.home-button')
  await click('.home-play')
  expect(host.querySelector('.pause-cover')).not.toBeNull()
  expect(host.querySelector('.header-actions button[aria-label="繼續遊戲"]')).not.toBeNull()
})
it('shows separate completion counts on home and starts the next stage in the selected difficulty', async () => {
  localStorage.setItem(TIDE_SAVE_KEY, '[1,2,101,201,202,203]')
  await act(() => root.render(createElement(App)))
  const choices = [...host.querySelectorAll('.home-difficulties button')]
  expect(choices.map(b => b.textContent)).toEqual(expect.arrayContaining([expect.stringContaining('2/100'), expect.stringContaining('1/100'), expect.stringContaining('3/100')]))
  await click('.home-difficulties button:nth-child(2)')
  await click('.home-links button:first-child')
  expect(host.querySelector('.collection-summary')!.textContent).toContain('普通已收藏 1 / 100')
  await click('.modal-close')
  expect(host.querySelector('.home-screen')).not.toBeNull()
  await click('.home-play')
  expect(host.querySelector('.level-bar')!.textContent).toContain('普通 · 第 02 關')
  expect(readTideProgress()).toEqual([1, 2, 101, 201, 202, 203])
})
it('names yellow mango everywhere and previews the actual next units and remaining queue count', async () => {
  localStorage.setItem(TIDE_SAVE_KEY, JSON.stringify(Array.from({ length: 40 }, (_, i) => i + 201)))
  localStorage.setItem('jellyOrbitDifficultyV1', 'hard')
  await renderGame()
  const level = levelsFor('hard')[40]
  const lane = level.lanes[1]
  const preview = host.querySelector('.lane:nth-child(2) .lane-sequence')!
  expect(preview.querySelectorAll('.sequence-dot')).toHaveLength(3)
  expect(preview.textContent).toContain(`還有 ${lane.length - 4} 隻`)
  const upcoming = host.querySelectorAll('.lane:nth-child(2) .upcoming-jelly')
  expect(upcoming[0].textContent).toContain(`${lane[1].energy} 發`)
  expect(upcoming[1].textContent).toContain(`${lane[2].energy} 發`)
  expect(host.querySelector('.lane:nth-child(3) .launch-button')!.getAttribute('aria-label')).toContain('芒果水母')
  await click('.queue-preview-button')
  expect(host.querySelectorAll('.queue-overview-lane')).toHaveLength(3)
  expect(host.querySelector('.queue-preview')!.textContent).toContain('芒果')
  expect(host.textContent).not.toContain('檸檬')
})
it('switches difficulty with separate unlocks and resets the game to the correct dock size', async () => {
  localStorage.setItem(TIDE_SAVE_KEY, '[1,2,3]')
  await renderGame()
  expect(host.querySelector('.level-bar')!.textContent).toContain('簡單 · 第 04 關')
  await click('.nav-button')
  await click('.difficulty-nav button:nth-child(2)')
  expect(host.querySelector('.collection-summary')!.textContent).toContain('普通已收藏 0 / 100')
  const stages = host.querySelectorAll<HTMLButtonElement>('.stage-map-entry')
  expect(stages).toHaveLength(10)
  expect(stages[0].disabled).toBe(false)
  expect(stages[1].disabled).toBe(true)
  await click('.stage-map-entry')
  expect(host.querySelector('.level-bar')!.textContent).toContain('普通 · 第 01 關')
  expect(host.querySelectorAll('.dock-slot')).toHaveLength(5)
  await click('.nav-button')
  await click('.difficulty-nav button:nth-child(3)')
  await click('.stage-map-entry')
  expect(host.querySelector('.level-bar')!.textContent).toContain('困難 · 第 01 關')
  expect(host.querySelectorAll('.dock-slot')).toHaveLength(4)
  expect(localStorage.getItem('jellyOrbitDifficultyV1')).toBe('hard')
  expect(readTideProgress()).toEqual([1, 2, 3])
  await act(() => root.unmount())
  root = createRoot(host)
  await renderGame()
  expect(host.querySelector('.level-bar')!.textContent).toContain('困難 · 第 01 關')
})
it('awards eligible challenges on the first clear, saves them under the correct difficulty ID and continues', async () => {
  localStorage.setItem(TIDE_SAVE_KEY, '[1]')
  localStorage.setItem('jellyOrbitDifficultyV1', 'normal')
  await renderGame()
  const level = levelsFor('normal')[0]
  await click('.game-tools button:last-child')
  const recordButton = [...host.querySelectorAll<HTMLButtonElement>('.settings-list button')].find(b => b.textContent!.includes('航海紀錄與挑戰'))!
  await act(() => recordButton.click())
  expect(host.querySelector('.challenge-badges')!.textContent).toContain(`≤ ${level.par} 次派遣`)
  expect(host.querySelectorAll('.challenge-badges .earned')).toHaveLength(0)
  expect(host.querySelector('.challenge-panel')!.textContent).toContain('首次通關也能達成')
  await click('.modal-close')
  let model = createTide(level)
  for (const id of level.solution!) {
    const pool = model.pool.findIndex(j => j.id === id)
    const lane = model.lanes.findIndex(l => l[0]?.id === id)
    await click(pool >= 0 ? `.dock-slot.occupied[data-jelly-id="${id}"]` : `.lane:nth-child(${lane + 1}) .launch-button`)
    model = launch(model, pool >= 0 ? 'pool' : 'lane', pool >= 0 ? pool : lane)
    while (model.swimmers.length && model.phase === 'playing') model = stepTide(model, level.size)
    await act(() => vi.advanceTimersByTime((level.size * 8 + 16) * TICK_MS))
  }
  expect(host.querySelector('.result-modal')).not.toBeNull()
  expect(readTideProgress()).toEqual([1, 101])
  expect(readRecords()[101].bestLaunches).toBe(level.solution!.length)
  expect(readRecords()[101]).toMatchObject({ efficient: true, noUndo: true })
  expect(host.querySelectorAll('.result-modal .challenge-badges .earned')).toHaveLength(2)
  expect(host.querySelector('.result-modal')!.textContent).not.toContain('下次重玩')
  expect(readRecords()[1]).toBeUndefined()
  await click('.result-modal .primary')
  expect(host.querySelector('.level-bar')!.textContent).toContain('普通 · 第 02 關')
  expect(host.querySelectorAll('.dock-slot.occupied')).toHaveLength(0)
})
it('shows reserved return slots and keeps the board in play and pauses while inspecting the full queue', async () => {
  localStorage.setItem('jellyOrbitDifficultyV1', 'hard')
  await renderGame()
  await click('.lane:nth-child(1) .launch-button')
  expect(host.querySelector('.dock-capacity')!.textContent).toBe('返航中 1 · 已停泊 0')
  expect(host.querySelector('.dock-available')!.textContent).toBe('可用 3 格')
  const reserved = host.querySelector('.dock-slot.reserved')!
  const berth = [...host.querySelectorAll('.dock-slot')].indexOf(reserved)
  const partner = reserved.getAttribute('data-jelly-id')
  expect(reserved.querySelector('img')).not.toBeNull()
  expect(reserved.textContent).toContain('返航中')
  expect(host.textContent).not.toContain('放大棋盤')
  expect(host.querySelectorAll('.pixel-board')).toHaveLength(1)
  await click('.queue-preview-button')
  expect(host.querySelectorAll('.queue-preview li')).toHaveLength(levelsFor('hard')[0].lanes.flat().length - 1)
  expect(host.querySelector('.queue-preview li')!.textContent).toContain('隊首')
  expect(host.querySelector('.queue-preview li')!.textContent).toContain('發泡泡')
  expect(host.querySelector('.queue-preview nav')).toBeNull()
  const lanes = host.querySelectorAll('.queue-overview-lane')
  expect(lanes).toHaveLength(3)
  for (let index = 0; index < 3; index++) {
    const remaining = levelsFor('hard')[0].lanes[index].slice(index === 0 ? 1 : 0)
    expect([...lanes[index].querySelectorAll('.queue-unit-name')].map(n => n.textContent)).toEqual(remaining.map(j => COLOR_NAMES[j.color]))
    expect([...lanes[index].querySelectorAll('.jelly-art b')].map(n => Number(n.textContent))).toEqual(remaining.map(j => j.energy))
    expect(host.querySelectorAll('.queue-overview-headings p')[index].textContent).toBe(`剩餘 ${remaining.length} 隻`)
  }
  const before = host.querySelector('.dock-capacity')!.textContent
  await act(() => vi.advanceTimersByTime(20000))
  expect(host.querySelector('.dock-capacity')!.textContent).toBe(before)
  await click('.queue-modal .primary')
  await act(() => vi.advanceTimersByTime(20000))
  expect(host.querySelector('.dock-capacity')!.textContent).toBe('返航中 0 · 已停泊 1')
  const parked = host.querySelectorAll('.dock-slot')[berth]
  expect(parked.classList.contains('occupied')).toBe(true)
  expect(parked.getAttribute('data-jelly-id')).toBe(partner)
  await click(`.dock-slot.occupied[data-jelly-id="${partner}"]`)
  expect(host.querySelectorAll('.dock-slot')[berth].classList.contains('reserved')).toBe(true)
})
it('keeps empty lanes in the overview and labels remaining heads, order and ammo accurately', async () => {
  await act(() => root.render(createElement(QueueOverview, { lanes: [[], [{ id: 'a', color: 'yellow', energy: 3 }, { id: 'b', color: 'aqua', energy: 2 }], []], imageFor: color => `/${color}.webp` })))
  expect(host.querySelectorAll('.queue-overview-lane')).toHaveLength(3)
  expect(host.querySelectorAll('.queue-overview-empty')).toHaveLength(2)
  expect([...host.querySelectorAll('.queue-overview-headings p')].map(n => n.textContent)).toEqual(['剩餘 0 隻', '剩餘 2 隻', '剩餘 0 隻'])
  const middle = host.querySelector('.queue-overview-lane:nth-child(2)')!
  expect(middle.querySelector('.queue-unit-head .queue-unit-name')!.textContent).toBe('芒果')
  expect(middle.querySelector('li:last-child .queue-position')!.textContent).toBe('第 2 隻')
  expect(middle.querySelector('li:last-child .queue-energy-long')!.textContent).toBe(' 發泡泡')
  expect(middle.querySelectorAll('img')[1].getAttribute('src')).toBe('/aqua.webp')
})
it('continues the current attempt from a compact chapter picker without resetting it', async () => {
  await renderGame()
  await click('.launch-button')
  await click('.nav-button')
  expect(host.querySelector('select')!.options).toHaveLength(10)
  expect(host.querySelector('.continue-journey')!.textContent).toContain('第 01 關')
  await click('.continue-journey')
  expect(host.querySelector('[role="dialog"]')).toBeNull()
  expect(host.querySelector('.dock-capacity')!.textContent).toContain('返航中 1')
})
it('removes hints from controls and shows no-undo challenges without automatic legacy awards', async () => {
  localStorage.setItem(TIDE_SAVE_KEY, '[1]')
  localStorage.setItem('jellyOrbitRecordsV1', '{"1":{"bestLaunches":10,"bestCombo":6,"noHint":true,"efficient":true}}')
  await renderGame()
  expect(host.querySelectorAll('.game-tools button')).toHaveLength(3)
  expect(host.querySelector('.game-tools')!.textContent).not.toContain('提示')
  await click('.nav-button')
  await click('.stage-map-entry')
  await click('.game-tools button:last-child')
  const recordButton = [...host.querySelectorAll<HTMLButtonElement>('.settings-list button')].find(b => b.textContent!.includes('航海紀錄與挑戰'))!
  await act(() => recordButton.click())
  expect(host.querySelector('.record-content')!.textContent).not.toContain('提示')
  expect(host.querySelector('.challenge-badges')!.textContent).toContain('不用撤回')
  expect(host.querySelector('.challenge-badges span:last-child')!.classList.contains('earned')).toBe(false)
})
